// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: proto/basichotstuffpb/basichotstuff.proto

package basichotstuffpb

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	commonpb "hxy352/src/proto/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	ClientAddress string                 `protobuf:"bytes,2,opt,name=clientAddress,proto3" json:"clientAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Request) GetClientAddress() string {
	if x != nil {
		return x.ClientAddress
	}
	return ""
}

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          commonpb.MessageType   `protobuf:"varint,1,opt,name=Type,proto3,enum=commonpb.MessageType" json:"Type,omitempty"` // Type of the message
	View          uint64                 `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
	Block         *Block                 `protobuf:"bytes,3,opt,name=Block,proto3" json:"Block,omitempty"`
	PartialCert   *PartialCert           `protobuf:"bytes,4,opt,name=PartialCert,proto3" json:"PartialCert,omitempty"`
	QC            *QuorumCert            `protobuf:"bytes,5,opt,name=QC,proto3" json:"QC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{1}
}

func (x *Msg) GetType() commonpb.MessageType {
	if x != nil {
		return x.Type
	}
	return commonpb.MessageType(0)
}

func (x *Msg) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Msg) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Msg) GetPartialCert() *PartialCert {
	if x != nil {
		return x.PartialCert
	}
	return nil
}

func (x *Msg) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

type BlockHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHash) Reset() {
	*x = BlockHash{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHash) ProtoMessage() {}

func (x *BlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHash.ProtoReflect.Descriptor instead.
func (*BlockHash) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{2}
}

func (x *BlockHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        []byte                 `protobuf:"bytes,1,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	View          uint64                 `protobuf:"varint,3,opt,name=View,proto3" json:"View,omitempty"`
	Command       []byte                 `protobuf:"bytes,4,opt,name=Command,proto3" json:"Command,omitempty"`
	QC            *QuorumCert            `protobuf:"bytes,5,opt,name=QC,proto3" json:"QC,omitempty"`
	Proposer      uint32                 `protobuf:"varint,6,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Block) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *Block) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Block) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *Block) GetProposer() uint32 {
	if x != nil {
		return x.Proposer
	}
	return 0
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ECDSASignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        uint32                 `protobuf:"varint,1,opt,name=Signer,proto3" json:"Signer,omitempty"`
	R             []byte                 `protobuf:"bytes,2,opt,name=R,proto3" json:"R,omitempty"`
	S             []byte                 `protobuf:"bytes,3,opt,name=S,proto3" json:"S,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSASignature) Reset() {
	*x = ECDSASignature{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSASignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSASignature) ProtoMessage() {}

func (x *ECDSASignature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSASignature.ProtoReflect.Descriptor instead.
func (*ECDSASignature) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{4}
}

func (x *ECDSASignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *ECDSASignature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *ECDSASignature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sig:
	//
	//	*Signature_ECDSASig
	Sig           isSignature_Sig `protobuf_oneof:"Sig"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{5}
}

func (x *Signature) GetSig() isSignature_Sig {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Signature) GetECDSASig() *ECDSASignature {
	if x != nil {
		if x, ok := x.Sig.(*Signature_ECDSASig); ok {
			return x.ECDSASig
		}
	}
	return nil
}

type isSignature_Sig interface {
	isSignature_Sig()
}

type Signature_ECDSASig struct {
	ECDSASig *ECDSASignature `protobuf:"bytes,1,opt,name=ECDSASig,proto3,oneof"`
}

func (*Signature_ECDSASig) isSignature_Sig() {}

type PartialCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           *QuorumSignature       `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialCert) Reset() {
	*x = PartialCert{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialCert) ProtoMessage() {}

func (x *PartialCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialCert.ProtoReflect.Descriptor instead.
func (*PartialCert) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{6}
}

func (x *PartialCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PartialCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type ECDSAMultiSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigs          []*ECDSASignature      `protobuf:"bytes,1,rep,name=Sigs,proto3" json:"Sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSAMultiSignature) Reset() {
	*x = ECDSAMultiSignature{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSAMultiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSAMultiSignature) ProtoMessage() {}

func (x *ECDSAMultiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSAMultiSignature.ProtoReflect.Descriptor instead.
func (*ECDSAMultiSignature) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{7}
}

func (x *ECDSAMultiSignature) GetSigs() []*ECDSASignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type QuorumSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Sig:
	//
	//	*QuorumSignature_ECDSASigs
	Sig           isQuorumSignature_Sig `protobuf_oneof:"Sig"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumSignature) Reset() {
	*x = QuorumSignature{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumSignature) ProtoMessage() {}

func (x *QuorumSignature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumSignature.ProtoReflect.Descriptor instead.
func (*QuorumSignature) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{8}
}

func (x *QuorumSignature) GetSig() isQuorumSignature_Sig {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumSignature) GetECDSASigs() *ECDSAMultiSignature {
	if x != nil {
		if x, ok := x.Sig.(*QuorumSignature_ECDSASigs); ok {
			return x.ECDSASigs
		}
	}
	return nil
}

type isQuorumSignature_Sig interface {
	isQuorumSignature_Sig()
}

type QuorumSignature_ECDSASigs struct {
	ECDSASigs *ECDSAMultiSignature `protobuf:"bytes,1,opt,name=ECDSASigs,proto3,oneof"`
}

func (*QuorumSignature_ECDSASigs) isQuorumSignature_Sig() {}

type QuorumCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sig           *QuorumSignature       `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	View          uint64                 `protobuf:"varint,2,opt,name=View,proto3" json:"View,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Type          commonpb.MessageType   `protobuf:"varint,4,opt,name=Type,proto3,enum=commonpb.MessageType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumCert) Reset() {
	*x = QuorumCert{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCert) ProtoMessage() {}

func (x *QuorumCert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCert.ProtoReflect.Descriptor instead.
func (*QuorumCert) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{9}
}

func (x *QuorumCert) GetSig() *QuorumSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumCert) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *QuorumCert) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *QuorumCert) GetType() commonpb.MessageType {
	if x != nil {
		return x.Type
	}
	return commonpb.MessageType(0)
}

type SyncInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QC            *QuorumCert            `protobuf:"bytes,1,opt,name=QC,proto3" json:"QC,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncInfo) Reset() {
	*x = SyncInfo{}
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInfo) ProtoMessage() {}

func (x *SyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInfo.ProtoReflect.Descriptor instead.
func (*SyncInfo) Descriptor() ([]byte, []int) {
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP(), []int{10}
}

func (x *SyncInfo) GetQC() *QuorumCert {
	if x != nil {
		return x.QC
	}
	return nil
}

var File_proto_basichotstuffpb_basichotstuff_proto protoreflect.FileDescriptor

const file_proto_basichotstuffpb_basichotstuff_proto_rawDesc = "" +
	"\n" +
	")proto/basichotstuffpb/basichotstuff.proto\x12\x0fbasichotstuffpb\x1a\fgorums.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bproto/commonpb/common.proto\"A\n" +
	"\aRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12$\n" +
	"\rclientAddress\x18\x02 \x01(\tR\rclientAddress\"\xdf\x01\n" +
	"\x03Msg\x12)\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x15.commonpb.MessageTypeR\x04Type\x12\x12\n" +
	"\x04View\x18\x02 \x01(\x04R\x04View\x12,\n" +
	"\x05Block\x18\x03 \x01(\v2\x16.basichotstuffpb.BlockR\x05Block\x12>\n" +
	"\vPartialCert\x18\x04 \x01(\v2\x1c.basichotstuffpb.PartialCertR\vPartialCert\x12+\n" +
	"\x02QC\x18\x05 \x01(\v2\x1b.basichotstuffpb.QuorumCertR\x02QC\"\x1f\n" +
	"\tBlockHash\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\fR\x04Hash\"\xe4\x01\n" +
	"\x05Block\x12\x16\n" +
	"\x06Parent\x18\x01 \x01(\fR\x06Parent\x12\x12\n" +
	"\x04Hash\x18\x02 \x01(\fR\x04Hash\x12\x12\n" +
	"\x04View\x18\x03 \x01(\x04R\x04View\x12\x18\n" +
	"\aCommand\x18\x04 \x01(\fR\aCommand\x12+\n" +
	"\x02QC\x18\x05 \x01(\v2\x1b.basichotstuffpb.QuorumCertR\x02QC\x12\x1a\n" +
	"\bProposer\x18\x06 \x01(\rR\bProposer\x128\n" +
	"\tTimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\"D\n" +
	"\x0eECDSASignature\x12\x16\n" +
	"\x06Signer\x18\x01 \x01(\rR\x06Signer\x12\f\n" +
	"\x01R\x18\x02 \x01(\fR\x01R\x12\f\n" +
	"\x01S\x18\x03 \x01(\fR\x01S\"Q\n" +
	"\tSignature\x12=\n" +
	"\bECDSASig\x18\x01 \x01(\v2\x1f.basichotstuffpb.ECDSASignatureH\x00R\bECDSASigB\x05\n" +
	"\x03Sig\"U\n" +
	"\vPartialCert\x122\n" +
	"\x03Sig\x18\x01 \x01(\v2 .basichotstuffpb.QuorumSignatureR\x03Sig\x12\x12\n" +
	"\x04Hash\x18\x02 \x01(\fR\x04Hash\"J\n" +
	"\x13ECDSAMultiSignature\x123\n" +
	"\x04Sigs\x18\x01 \x03(\v2\x1f.basichotstuffpb.ECDSASignatureR\x04Sigs\"^\n" +
	"\x0fQuorumSignature\x12D\n" +
	"\tECDSASigs\x18\x01 \x01(\v2$.basichotstuffpb.ECDSAMultiSignatureH\x00R\tECDSASigsB\x05\n" +
	"\x03Sig\"\x93\x01\n" +
	"\n" +
	"QuorumCert\x122\n" +
	"\x03Sig\x18\x01 \x01(\v2 .basichotstuffpb.QuorumSignatureR\x03Sig\x12\x12\n" +
	"\x04View\x18\x02 \x01(\x04R\x04View\x12\x12\n" +
	"\x04Hash\x18\x03 \x01(\fR\x04Hash\x12)\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x15.commonpb.MessageTypeR\x04Type\"7\n" +
	"\bSyncInfo\x12+\n" +
	"\x02QC\x18\x01 \x01(\v2\x1b.basichotstuffpb.QuorumCertR\x02QC2\xdb\x04\n" +
	"\rBasicHotStuff\x12=\n" +
	"\aNewView\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12=\n" +
	"\aPrepare\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12A\n" +
	"\vPrepareVote\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12?\n" +
	"\tPreCommit\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12C\n" +
	"\rPreCommitVote\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12<\n" +
	"\x06Commit\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12@\n" +
	"\n" +
	"CommitVote\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12<\n" +
	"\x06Decide\x12\x14.basichotstuffpb.Msg\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01\x12E\n" +
	"\vSendRequest\x12\x18.basichotstuffpb.Request\x1a\x16.google.protobuf.Empty\"\x04\x90\xb5\x18\x01B\"Z hxy352/src/proto/basichotstuffpbb\x06proto3"

var (
	file_proto_basichotstuffpb_basichotstuff_proto_rawDescOnce sync.Once
	file_proto_basichotstuffpb_basichotstuff_proto_rawDescData []byte
)

func file_proto_basichotstuffpb_basichotstuff_proto_rawDescGZIP() []byte {
	file_proto_basichotstuffpb_basichotstuff_proto_rawDescOnce.Do(func() {
		file_proto_basichotstuffpb_basichotstuff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_basichotstuffpb_basichotstuff_proto_rawDesc), len(file_proto_basichotstuffpb_basichotstuff_proto_rawDesc)))
	})
	return file_proto_basichotstuffpb_basichotstuff_proto_rawDescData
}

var file_proto_basichotstuffpb_basichotstuff_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_basichotstuffpb_basichotstuff_proto_goTypes = []any{
	(*Request)(nil),               // 0: basichotstuffpb.Request
	(*Msg)(nil),                   // 1: basichotstuffpb.Msg
	(*BlockHash)(nil),             // 2: basichotstuffpb.BlockHash
	(*Block)(nil),                 // 3: basichotstuffpb.Block
	(*ECDSASignature)(nil),        // 4: basichotstuffpb.ECDSASignature
	(*Signature)(nil),             // 5: basichotstuffpb.Signature
	(*PartialCert)(nil),           // 6: basichotstuffpb.PartialCert
	(*ECDSAMultiSignature)(nil),   // 7: basichotstuffpb.ECDSAMultiSignature
	(*QuorumSignature)(nil),       // 8: basichotstuffpb.QuorumSignature
	(*QuorumCert)(nil),            // 9: basichotstuffpb.QuorumCert
	(*SyncInfo)(nil),              // 10: basichotstuffpb.SyncInfo
	(commonpb.MessageType)(0),     // 11: commonpb.MessageType
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_proto_basichotstuffpb_basichotstuff_proto_depIdxs = []int32{
	11, // 0: basichotstuffpb.Msg.Type:type_name -> commonpb.MessageType
	3,  // 1: basichotstuffpb.Msg.Block:type_name -> basichotstuffpb.Block
	6,  // 2: basichotstuffpb.Msg.PartialCert:type_name -> basichotstuffpb.PartialCert
	9,  // 3: basichotstuffpb.Msg.QC:type_name -> basichotstuffpb.QuorumCert
	9,  // 4: basichotstuffpb.Block.QC:type_name -> basichotstuffpb.QuorumCert
	12, // 5: basichotstuffpb.Block.Timestamp:type_name -> google.protobuf.Timestamp
	4,  // 6: basichotstuffpb.Signature.ECDSASig:type_name -> basichotstuffpb.ECDSASignature
	8,  // 7: basichotstuffpb.PartialCert.Sig:type_name -> basichotstuffpb.QuorumSignature
	4,  // 8: basichotstuffpb.ECDSAMultiSignature.Sigs:type_name -> basichotstuffpb.ECDSASignature
	7,  // 9: basichotstuffpb.QuorumSignature.ECDSASigs:type_name -> basichotstuffpb.ECDSAMultiSignature
	8,  // 10: basichotstuffpb.QuorumCert.Sig:type_name -> basichotstuffpb.QuorumSignature
	11, // 11: basichotstuffpb.QuorumCert.Type:type_name -> commonpb.MessageType
	9,  // 12: basichotstuffpb.SyncInfo.QC:type_name -> basichotstuffpb.QuorumCert
	1,  // 13: basichotstuffpb.BasicHotStuff.NewView:input_type -> basichotstuffpb.Msg
	1,  // 14: basichotstuffpb.BasicHotStuff.Prepare:input_type -> basichotstuffpb.Msg
	1,  // 15: basichotstuffpb.BasicHotStuff.PrepareVote:input_type -> basichotstuffpb.Msg
	1,  // 16: basichotstuffpb.BasicHotStuff.PreCommit:input_type -> basichotstuffpb.Msg
	1,  // 17: basichotstuffpb.BasicHotStuff.PreCommitVote:input_type -> basichotstuffpb.Msg
	1,  // 18: basichotstuffpb.BasicHotStuff.Commit:input_type -> basichotstuffpb.Msg
	1,  // 19: basichotstuffpb.BasicHotStuff.CommitVote:input_type -> basichotstuffpb.Msg
	1,  // 20: basichotstuffpb.BasicHotStuff.Decide:input_type -> basichotstuffpb.Msg
	0,  // 21: basichotstuffpb.BasicHotStuff.SendRequest:input_type -> basichotstuffpb.Request
	13, // 22: basichotstuffpb.BasicHotStuff.NewView:output_type -> google.protobuf.Empty
	13, // 23: basichotstuffpb.BasicHotStuff.Prepare:output_type -> google.protobuf.Empty
	13, // 24: basichotstuffpb.BasicHotStuff.PrepareVote:output_type -> google.protobuf.Empty
	13, // 25: basichotstuffpb.BasicHotStuff.PreCommit:output_type -> google.protobuf.Empty
	13, // 26: basichotstuffpb.BasicHotStuff.PreCommitVote:output_type -> google.protobuf.Empty
	13, // 27: basichotstuffpb.BasicHotStuff.Commit:output_type -> google.protobuf.Empty
	13, // 28: basichotstuffpb.BasicHotStuff.CommitVote:output_type -> google.protobuf.Empty
	13, // 29: basichotstuffpb.BasicHotStuff.Decide:output_type -> google.protobuf.Empty
	13, // 30: basichotstuffpb.BasicHotStuff.SendRequest:output_type -> google.protobuf.Empty
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_basichotstuffpb_basichotstuff_proto_init() }
func file_proto_basichotstuffpb_basichotstuff_proto_init() {
	if File_proto_basichotstuffpb_basichotstuff_proto != nil {
		return
	}
	file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[5].OneofWrappers = []any{
		(*Signature_ECDSASig)(nil),
	}
	file_proto_basichotstuffpb_basichotstuff_proto_msgTypes[8].OneofWrappers = []any{
		(*QuorumSignature_ECDSASigs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_basichotstuffpb_basichotstuff_proto_rawDesc), len(file_proto_basichotstuffpb_basichotstuff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_basichotstuffpb_basichotstuff_proto_goTypes,
		DependencyIndexes: file_proto_basichotstuffpb_basichotstuff_proto_depIdxs,
		MessageInfos:      file_proto_basichotstuffpb_basichotstuff_proto_msgTypes,
	}.Build()
	File_proto_basichotstuffpb_basichotstuff_proto = out.File
	file_proto_basichotstuffpb_basichotstuff_proto_goTypes = nil
	file_proto_basichotstuffpb_basichotstuff_proto_depIdxs = nil
}
