syntax = "proto3";

package basichotstuffpb;

import "gorums.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "proto/commonpb/common.proto";

option go_package = "hxy352/src/proto/basichotstuffpb";

service BasicHotStuff {
  rpc NewView(Msg) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc NewViewBasic(Msg) returns (google.protobuf.Empty) {
    option (gorums.unicast) = true;
  }

  rpc Prepare(Msg) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc PrepareVote(Msg) returns (google.protobuf.Empty) {
    option (gorums.unicast) = true;
  }

  rpc PreCommit(Msg) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc PreCommitVote(Msg) returns (google.protobuf.Empty) {
    option (gorums.unicast) = true;
  }

  rpc Commit(Msg) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc CommitVote(Msg) returns (google.protobuf.Empty) {
    option (gorums.unicast) = true;
  }

  rpc Decide(Msg) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc SendRequest(Request) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc WishNextView(Msg) returns (google.protobuf.Empty) {
    option (gorums.unicast) = true;
  }

  rpc Timeout(Msg) returns (google.protobuf.Empty) {
    option (gorums.multicast) = true;
  }

  rpc TimeoutVote(Msg) returns (google.protobuf.Empty) {
    option (gorums.unicast) = true;
  }
}

message Request {
  string cmd = 1;
  string clientAddress = 2;
}

message Msg {
  commonpb.MessageType Type = 1; // Type of the message
  uint64 View = 2;
  Block Block = 3;
  PartialCert PartialCert = 4;
  QuorumCert QC = 5;
  uint32 ReplicaId = 6;

  // for wish next view and timeout
  QuorumSignature ViewSig = 7;

  // for timeout
  TimeoutCert TC = 8;
  QuorumSignature MsgSig = 9;
}

message BlockHash {
  bytes Hash = 1;
}

message Block {
  bytes Parent = 1;
  bytes Hash = 2;
  uint64 View = 3;
  bytes Command = 4;
  QuorumCert QC = 5;
  uint32 Proposer = 6;
  google.protobuf.Timestamp Timestamp =7;
}

message ECDSASignature {
  uint32 Signer = 1;
  bytes R = 2;
  bytes S = 3;
}

message Signature {
  oneof Sig {
    ECDSASignature ECDSASig = 1;
  }
}

message PartialCert {
  QuorumSignature Sig = 1;
  bytes Hash = 2;
}

message ECDSAMultiSignature { repeated ECDSASignature Sigs = 1; }

message QuorumSignature {
  oneof Sig {
    ECDSAMultiSignature ECDSASigs = 1;
  }
}

message QuorumCert {
  QuorumSignature Sig = 1;
  uint64 View = 2;
  bytes Hash = 3;
  commonpb.MessageType Type = 4;
}

message TimeoutCert {
  QuorumSignature Sig = 1;
  uint64 View = 2;
}

message SyncInfo {
  QuorumCert QC = 1;
}