services:
  bhs-replica0:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--id=0"
      - "--fault_number=0"
      - "--pacemaker_loaded=false"
      - "--total_number=4"
    volumes:
      - ../../configs:/app/configs:ro
      - ../../configs/config-map-docker.yaml:/app/configs/config-map.yaml:ro
      - ../../files:/app/files:rw
      - ../../logs/main_0.log:/app/logs/app.log:rw
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"

  bhs-replica1:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--id=1"
      - "--fault_number=0"
      - "--pacemaker_loaded=false"
      - "--total_number=4"
    volumes:
      - ../../configs:/app/configs:ro
      # 2. 覆盖 config-map 为 docker 用的版本
      - ../../configs/config-map-docker.yaml:/app/configs/config-map.yaml:ro
      - ../../files:/app/files:rw
      - ../../logs/main_1.log:/app/logs/app.log:rw
    ports:
      - "8001:8001"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"

  bhs-replica2:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--id=2"
      - "--fault_number=0"
      - "--pacemaker_loaded=false"
      - "--total_number=4"
    volumes:
      - ../../configs:/app/configs:ro
      - ../../configs/config-map-docker.yaml:/app/configs/config-map.yaml:ro
      - ../../files:/app/files:rw
      - ../../logs/main_2.log:/app/logs/app.log:rw
    ports:
      - "8002:8002"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"

  bhs-replica3:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--id=3"
      - "--fault_number=0"
      - "--pacemaker_loaded=false"
      - "--total_number=4"
    volumes:
      - ../../configs:/app/configs:ro
      - ../../configs/config-map-docker.yaml:/app/configs/config-map.yaml:ro
      - ../../files:/app/files:rw
      - ../../logs/main_3.log:/app/logs/app.log:rw
    ports:
      - "8003:8003"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"

  bhs-client:
    image: hxy352-main:latest
    command:
      - "bhs-client"
      - "--fault_number=0"
      - "--pacemaker_loaded=false"
      - "--total_number=4"
    volumes:
      - ../../configs:/app/configs:ro
      - ../../configs/config-map-docker.yaml:/app/configs/config-map.yaml:ro
      - ../../files:/app/files:rw
      - ../../logs/main_client.log:/app/logs/app.log:rw
    ports:
      - "9000:9000"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"
    depends_on:
      - bhs-replica0
      - bhs-replica1
      - bhs-replica2
      - bhs-replica3
