
services:
  bhs-replica0:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--config=/app/configs/config-map-docker.yaml"
      - "--id=0"
    volumes:
      - ../../configs:/app/configs:ro
    ports:
      - "8000:8000"
#    restart: always
#    labels:
#      private_api_go_sdk: "true"
    logging:
#      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"
#    networks:
#      - network

  bhs-replica1:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--config=/app/configs/config-map-docker.yaml"
      - "--id=1"
    volumes:
      - ../../configs:/app/configs:ro
    ports:
      - "8001:8001"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"
#    networks:
#      - network

  bhs-replica2:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--config=/app/configs/config-map-docker.yaml"
      - "--id=2"
    volumes:
      - ../../configs:/app/configs:ro
    ports:
      - "8002:8002"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"
#    networks:
#      - network

  bhs-replica3:
    image: hxy352-main:latest
    command:
      - "bhs"
      - "--config=/app/configs/config-map-docker.yaml"
      - "--id=3"
    volumes:
      - ../../configs:/app/configs:ro
    ports:
      - "8003:8003"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"
#    networks:
#      - network

  bhs-client:
    image: hxy352-main:latest
    command:
      - "bhs-client"
      - "--config=/app/configs/config-map-docker.yaml"
    volumes:
      - ../../configs:/app/configs:ro
    ports:
      - "9000:9000"
    logging:
      options:
        max-size: "50m"
        max-file: "1"
        compress: "false"
#    networks:
#      - network
    depends_on:
      - bhs-replica0
      - bhs-replica1
      - bhs-replica2
      - bhs-replica3

#networks:
#  network:
#    driver: bridge
##    ipam:
##      config:
##        - subnet: 172.20.0.0/16
