// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.4
// source: proto/commonpb/common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Unknown       MessageType = 0
	MessageType_NewView       MessageType = 1
	MessageType_Prepare       MessageType = 2
	MessageType_PrepareVote   MessageType = 3
	MessageType_PreCommit     MessageType = 4
	MessageType_PreCommitVote MessageType = 5
	MessageType_Commit        MessageType = 6
	MessageType_CommitVote    MessageType = 7
	MessageType_Decide        MessageType = 8
	MessageType_WishNextView  MessageType = 9
	MessageType_Timeout       MessageType = 10
	MessageType_TimeoutVote   MessageType = 11
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "Unknown",
		1:  "NewView",
		2:  "Prepare",
		3:  "PrepareVote",
		4:  "PreCommit",
		5:  "PreCommitVote",
		6:  "Commit",
		7:  "CommitVote",
		8:  "Decide",
		9:  "WishNextView",
		10: "Timeout",
		11: "TimeoutVote",
	}
	MessageType_value = map[string]int32{
		"Unknown":       0,
		"NewView":       1,
		"Prepare":       2,
		"PrepareVote":   3,
		"PreCommit":     4,
		"PreCommitVote": 5,
		"Commit":        6,
		"CommitVote":    7,
		"Decide":        8,
		"WishNextView":  9,
		"Timeout":       10,
		"TimeoutVote":   11,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_commonpb_common_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_commonpb_common_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_commonpb_common_proto_rawDescGZIP(), []int{0}
}

var File_proto_commonpb_common_proto protoreflect.FileDescriptor

const file_proto_commonpb_common_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/commonpb/common.proto\x12\bcommonpb*\xbf\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aNewView\x10\x01\x12\v\n" +
	"\aPrepare\x10\x02\x12\x0f\n" +
	"\vPrepareVote\x10\x03\x12\r\n" +
	"\tPreCommit\x10\x04\x12\x11\n" +
	"\rPreCommitVote\x10\x05\x12\n" +
	"\n" +
	"\x06Commit\x10\x06\x12\x0e\n" +
	"\n" +
	"CommitVote\x10\a\x12\n" +
	"\n" +
	"\x06Decide\x10\b\x12\x10\n" +
	"\fWishNextView\x10\t\x12\v\n" +
	"\aTimeout\x10\n" +
	"\x12\x0f\n" +
	"\vTimeoutVote\x10\vB\x1bZ\x19hxy352/src/proto/commonpbb\x06proto3"

var (
	file_proto_commonpb_common_proto_rawDescOnce sync.Once
	file_proto_commonpb_common_proto_rawDescData []byte
)

func file_proto_commonpb_common_proto_rawDescGZIP() []byte {
	file_proto_commonpb_common_proto_rawDescOnce.Do(func() {
		file_proto_commonpb_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commonpb_common_proto_rawDesc), len(file_proto_commonpb_common_proto_rawDesc)))
	})
	return file_proto_commonpb_common_proto_rawDescData
}

var file_proto_commonpb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_commonpb_common_proto_goTypes = []any{
	(MessageType)(0), // 0: commonpb.MessageType
}
var file_proto_commonpb_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_commonpb_common_proto_init() }
func file_proto_commonpb_common_proto_init() {
	if File_proto_commonpb_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commonpb_common_proto_rawDesc), len(file_proto_commonpb_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_commonpb_common_proto_goTypes,
		DependencyIndexes: file_proto_commonpb_common_proto_depIdxs,
		EnumInfos:         file_proto_commonpb_common_proto_enumTypes,
	}.Build()
	File_proto_commonpb_common_proto = out.File
	file_proto_commonpb_common_proto_goTypes = nil
	file_proto_commonpb_common_proto_depIdxs = nil
}
